### ISSUE TITLE
Dependency 'curlpp' is broken

### ISSUE THREAD

**Issue by Deluze** [Deluze/qpang-essence-emulator#7]
It seems like this dependency hasn't been maintained for about 3 years, and with the new vcpkg and cmake versions coming out it looks like this dependency is unable to be build.

This dependency should be removed using web requests within our server code, we could do this by either implementing bcrypt implementation on the emulator side, or use the native curl instead of curlpp.

Though, implementing a bcrypt library seems more efficient since then we don't have to depend on an external API.

**Comment by YestinJarrett** [comment]
I say, implement the bcrypt library, more efficient = better
